/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.hrms.model.impl;

import com.hrms.model.EmployeeType;

import com.hrms.service.EmployeeTypeLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the EmployeeType service. Represents a row in the &quot;HRMS_EmployeeType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EmployeeTypeImpl}.
 * </p>
 *
 * @author bhavik
 * @see EmployeeTypeImpl
 * @see com.hrms.model.EmployeeType
 * @generated
 */
public abstract class EmployeeTypeBaseImpl extends EmployeeTypeModelImpl
	implements EmployeeType {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a employee type model instance should use the {@link EmployeeType} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			EmployeeTypeLocalServiceUtil.addEmployeeType(this);
		}
		else {
			EmployeeTypeLocalServiceUtil.updateEmployeeType(this);
		}
	}
}