/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.hrms.model.impl;

import com.hrms.model.EmployeeAchivement;
import com.hrms.model.EmployeeAchivementModel;
import com.hrms.model.EmployeeAchivementSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the EmployeeAchivement service. Represents a row in the &quot;HRMS_EmployeeAchivement&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.hrms.model.EmployeeAchivementModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EmployeeAchivementImpl}.
 * </p>
 *
 * @author yashpalsinh
 * @see EmployeeAchivementImpl
 * @see com.hrms.model.EmployeeAchivement
 * @see com.hrms.model.EmployeeAchivementModel
 * @generated
 */
@JSON(strict = true)
public class EmployeeAchivementModelImpl extends BaseModelImpl<EmployeeAchivement>
	implements EmployeeAchivementModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a employee achivement model instance should use the {@link com.hrms.model.EmployeeAchivement} interface instead.
	 */
	public static final String TABLE_NAME = "HRMS_EmployeeAchivement";
	public static final Object[][] TABLE_COLUMNS = {
			{ "employeeAchivementId", Types.BIGINT },
			{ "achivedBy", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "achivementDate", Types.TIMESTAMP },
			{ "achivementTitle", Types.VARCHAR },
			{ "achivementDiscription", Types.VARCHAR },
			{ "status", Types.BOOLEAN },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "createBy", Types.BIGINT },
			{ "modifiedBy", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table HRMS_EmployeeAchivement (employeeAchivementId LONG not null primary key,achivedBy LONG,groupId LONG,companyId LONG,achivementDate DATE null,achivementTitle VARCHAR(75) null,achivementDiscription VARCHAR(75) null,status BOOLEAN,createDate DATE null,modifiedDate DATE null,createBy LONG,modifiedBy LONG)";
	public static final String TABLE_SQL_DROP = "drop table HRMS_EmployeeAchivement";
	public static final String ORDER_BY_JPQL = " ORDER BY employeeAchivement.employeeAchivementId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY HRMS_EmployeeAchivement.employeeAchivementId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.hrms.model.EmployeeAchivement"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.hrms.model.EmployeeAchivement"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.hrms.model.EmployeeAchivement"),
			true);
	public static long CREATEBY_COLUMN_BITMASK = 1L;
	public static long MODIFIEDBY_COLUMN_BITMASK = 2L;
	public static long EMPLOYEEACHIVEMENTID_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static EmployeeAchivement toModel(EmployeeAchivementSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		EmployeeAchivement model = new EmployeeAchivementImpl();

		model.setEmployeeAchivementId(soapModel.getEmployeeAchivementId());
		model.setAchivedBy(soapModel.getAchivedBy());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setAchivementDate(soapModel.getAchivementDate());
		model.setAchivementTitle(soapModel.getAchivementTitle());
		model.setAchivementDiscription(soapModel.getAchivementDiscription());
		model.setStatus(soapModel.getStatus());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setCreateBy(soapModel.getCreateBy());
		model.setModifiedBy(soapModel.getModifiedBy());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<EmployeeAchivement> toModels(
		EmployeeAchivementSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<EmployeeAchivement> models = new ArrayList<EmployeeAchivement>(soapModels.length);

		for (EmployeeAchivementSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.hrms.model.EmployeeAchivement"));

	public EmployeeAchivementModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _employeeAchivementId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEmployeeAchivementId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _employeeAchivementId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EmployeeAchivement.class;
	}

	@Override
	public String getModelClassName() {
		return EmployeeAchivement.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("employeeAchivementId", getEmployeeAchivementId());
		attributes.put("achivedBy", getAchivedBy());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("achivementDate", getAchivementDate());
		attributes.put("achivementTitle", getAchivementTitle());
		attributes.put("achivementDiscription", getAchivementDiscription());
		attributes.put("status", getStatus());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("createBy", getCreateBy());
		attributes.put("modifiedBy", getModifiedBy());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long employeeAchivementId = (Long)attributes.get("employeeAchivementId");

		if (employeeAchivementId != null) {
			setEmployeeAchivementId(employeeAchivementId);
		}

		Long achivedBy = (Long)attributes.get("achivedBy");

		if (achivedBy != null) {
			setAchivedBy(achivedBy);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Date achivementDate = (Date)attributes.get("achivementDate");

		if (achivementDate != null) {
			setAchivementDate(achivementDate);
		}

		String achivementTitle = (String)attributes.get("achivementTitle");

		if (achivementTitle != null) {
			setAchivementTitle(achivementTitle);
		}

		String achivementDiscription = (String)attributes.get(
				"achivementDiscription");

		if (achivementDiscription != null) {
			setAchivementDiscription(achivementDiscription);
		}

		Boolean status = (Boolean)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long createBy = (Long)attributes.get("createBy");

		if (createBy != null) {
			setCreateBy(createBy);
		}

		Long modifiedBy = (Long)attributes.get("modifiedBy");

		if (modifiedBy != null) {
			setModifiedBy(modifiedBy);
		}
	}

	@JSON
	@Override
	public long getEmployeeAchivementId() {
		return _employeeAchivementId;
	}

	@Override
	public void setEmployeeAchivementId(long employeeAchivementId) {
		_employeeAchivementId = employeeAchivementId;
	}

	@JSON
	@Override
	public long getAchivedBy() {
		return _achivedBy;
	}

	@Override
	public void setAchivedBy(long achivedBy) {
		_achivedBy = achivedBy;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public Date getAchivementDate() {
		return _achivementDate;
	}

	@Override
	public void setAchivementDate(Date achivementDate) {
		_achivementDate = achivementDate;
	}

	@JSON
	@Override
	public String getAchivementTitle() {
		if (_achivementTitle == null) {
			return StringPool.BLANK;
		}
		else {
			return _achivementTitle;
		}
	}

	@Override
	public void setAchivementTitle(String achivementTitle) {
		_achivementTitle = achivementTitle;
	}

	@JSON
	@Override
	public String getAchivementDiscription() {
		if (_achivementDiscription == null) {
			return StringPool.BLANK;
		}
		else {
			return _achivementDiscription;
		}
	}

	@Override
	public void setAchivementDiscription(String achivementDiscription) {
		_achivementDiscription = achivementDiscription;
	}

	@JSON
	@Override
	public boolean getStatus() {
		return _status;
	}

	@Override
	public boolean isStatus() {
		return _status;
	}

	@Override
	public void setStatus(boolean status) {
		_status = status;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getCreateBy() {
		return _createBy;
	}

	@Override
	public void setCreateBy(long createBy) {
		_columnBitmask |= CREATEBY_COLUMN_BITMASK;

		if (!_setOriginalCreateBy) {
			_setOriginalCreateBy = true;

			_originalCreateBy = _createBy;
		}

		_createBy = createBy;
	}

	public long getOriginalCreateBy() {
		return _originalCreateBy;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		_columnBitmask |= MODIFIEDBY_COLUMN_BITMASK;

		if (!_setOriginalModifiedBy) {
			_setOriginalModifiedBy = true;

			_originalModifiedBy = _modifiedBy;
		}

		_modifiedBy = modifiedBy;
	}

	public long getOriginalModifiedBy() {
		return _originalModifiedBy;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			EmployeeAchivement.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EmployeeAchivement toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (EmployeeAchivement)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EmployeeAchivementImpl employeeAchivementImpl = new EmployeeAchivementImpl();

		employeeAchivementImpl.setEmployeeAchivementId(getEmployeeAchivementId());
		employeeAchivementImpl.setAchivedBy(getAchivedBy());
		employeeAchivementImpl.setGroupId(getGroupId());
		employeeAchivementImpl.setCompanyId(getCompanyId());
		employeeAchivementImpl.setAchivementDate(getAchivementDate());
		employeeAchivementImpl.setAchivementTitle(getAchivementTitle());
		employeeAchivementImpl.setAchivementDiscription(getAchivementDiscription());
		employeeAchivementImpl.setStatus(getStatus());
		employeeAchivementImpl.setCreateDate(getCreateDate());
		employeeAchivementImpl.setModifiedDate(getModifiedDate());
		employeeAchivementImpl.setCreateBy(getCreateBy());
		employeeAchivementImpl.setModifiedBy(getModifiedBy());

		employeeAchivementImpl.resetOriginalValues();

		return employeeAchivementImpl;
	}

	@Override
	public int compareTo(EmployeeAchivement employeeAchivement) {
		long primaryKey = employeeAchivement.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof EmployeeAchivement)) {
			return false;
		}

		EmployeeAchivement employeeAchivement = (EmployeeAchivement)obj;

		long primaryKey = employeeAchivement.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		EmployeeAchivementModelImpl employeeAchivementModelImpl = this;

		employeeAchivementModelImpl._originalCreateBy = employeeAchivementModelImpl._createBy;

		employeeAchivementModelImpl._setOriginalCreateBy = false;

		employeeAchivementModelImpl._originalModifiedBy = employeeAchivementModelImpl._modifiedBy;

		employeeAchivementModelImpl._setOriginalModifiedBy = false;

		employeeAchivementModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<EmployeeAchivement> toCacheModel() {
		EmployeeAchivementCacheModel employeeAchivementCacheModel = new EmployeeAchivementCacheModel();

		employeeAchivementCacheModel.employeeAchivementId = getEmployeeAchivementId();

		employeeAchivementCacheModel.achivedBy = getAchivedBy();

		employeeAchivementCacheModel.groupId = getGroupId();

		employeeAchivementCacheModel.companyId = getCompanyId();

		Date achivementDate = getAchivementDate();

		if (achivementDate != null) {
			employeeAchivementCacheModel.achivementDate = achivementDate.getTime();
		}
		else {
			employeeAchivementCacheModel.achivementDate = Long.MIN_VALUE;
		}

		employeeAchivementCacheModel.achivementTitle = getAchivementTitle();

		String achivementTitle = employeeAchivementCacheModel.achivementTitle;

		if ((achivementTitle != null) && (achivementTitle.length() == 0)) {
			employeeAchivementCacheModel.achivementTitle = null;
		}

		employeeAchivementCacheModel.achivementDiscription = getAchivementDiscription();

		String achivementDiscription = employeeAchivementCacheModel.achivementDiscription;

		if ((achivementDiscription != null) &&
				(achivementDiscription.length() == 0)) {
			employeeAchivementCacheModel.achivementDiscription = null;
		}

		employeeAchivementCacheModel.status = getStatus();

		Date createDate = getCreateDate();

		if (createDate != null) {
			employeeAchivementCacheModel.createDate = createDate.getTime();
		}
		else {
			employeeAchivementCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			employeeAchivementCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			employeeAchivementCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		employeeAchivementCacheModel.createBy = getCreateBy();

		employeeAchivementCacheModel.modifiedBy = getModifiedBy();

		return employeeAchivementCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(25);

		sb.append("{employeeAchivementId=");
		sb.append(getEmployeeAchivementId());
		sb.append(", achivedBy=");
		sb.append(getAchivedBy());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", achivementDate=");
		sb.append(getAchivementDate());
		sb.append(", achivementTitle=");
		sb.append(getAchivementTitle());
		sb.append(", achivementDiscription=");
		sb.append(getAchivementDiscription());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", createBy=");
		sb.append(getCreateBy());
		sb.append(", modifiedBy=");
		sb.append(getModifiedBy());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(40);

		sb.append("<model><model-name>");
		sb.append("com.hrms.model.EmployeeAchivement");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>employeeAchivementId</column-name><column-value><![CDATA[");
		sb.append(getEmployeeAchivementId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>achivedBy</column-name><column-value><![CDATA[");
		sb.append(getAchivedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>achivementDate</column-name><column-value><![CDATA[");
		sb.append(getAchivementDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>achivementTitle</column-name><column-value><![CDATA[");
		sb.append(getAchivementTitle());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>achivementDiscription</column-name><column-value><![CDATA[");
		sb.append(getAchivementDiscription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createBy</column-name><column-value><![CDATA[");
		sb.append(getCreateBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedBy</column-name><column-value><![CDATA[");
		sb.append(getModifiedBy());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = EmployeeAchivement.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			EmployeeAchivement.class
		};
	private long _employeeAchivementId;
	private long _achivedBy;
	private long _groupId;
	private long _companyId;
	private Date _achivementDate;
	private String _achivementTitle;
	private String _achivementDiscription;
	private boolean _status;
	private Date _createDate;
	private Date _modifiedDate;
	private long _createBy;
	private long _originalCreateBy;
	private boolean _setOriginalCreateBy;
	private long _modifiedBy;
	private long _originalModifiedBy;
	private boolean _setOriginalModifiedBy;
	private long _columnBitmask;
	private EmployeeAchivement _escapedModel;
}