/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.hrms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Candidate service. Represents a row in the &quot;HRMS_Candidate&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.hrms.model.impl.CandidateModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.hrms.model.impl.CandidateImpl}.
 * </p>
 *
 * @author yashpalsinh
 * @see Candidate
 * @see com.hrms.model.impl.CandidateImpl
 * @see com.hrms.model.impl.CandidateModelImpl
 * @generated
 */
public interface CandidateModel extends BaseModel<Candidate> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a candidate model instance should use the {@link Candidate} interface instead.
	 */

	/**
	 * Returns the primary key of this candidate.
	 *
	 * @return the primary key of this candidate
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this candidate.
	 *
	 * @param primaryKey the primary key of this candidate
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the candidate ID of this candidate.
	 *
	 * @return the candidate ID of this candidate
	 */
	public long getCandidateId();

	/**
	 * Sets the candidate ID of this candidate.
	 *
	 * @param candidateId the candidate ID of this candidate
	 */
	public void setCandidateId(long candidateId);

	/**
	 * Returns the employee department ID of this candidate.
	 *
	 * @return the employee department ID of this candidate
	 */
	public long getEmployeeDepartmentId();

	/**
	 * Sets the employee department ID of this candidate.
	 *
	 * @param employeeDepartmentId the employee department ID of this candidate
	 */
	public void setEmployeeDepartmentId(long employeeDepartmentId);

	/**
	 * Returns the employee designation ID of this candidate.
	 *
	 * @return the employee designation ID of this candidate
	 */
	public long getEmployeeDesignationId();

	/**
	 * Sets the employee designation ID of this candidate.
	 *
	 * @param employeeDesignationId the employee designation ID of this candidate
	 */
	public void setEmployeeDesignationId(long employeeDesignationId);

	/**
	 * Returns the title of this candidate.
	 *
	 * @return the title of this candidate
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this candidate.
	 *
	 * @param title the title of this candidate
	 */
	public void setTitle(String title);

	/**
	 * Returns the first name of this candidate.
	 *
	 * @return the first name of this candidate
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this candidate.
	 *
	 * @param firstName the first name of this candidate
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the middle name of this candidate.
	 *
	 * @return the middle name of this candidate
	 */
	@AutoEscape
	public String getMiddleName();

	/**
	 * Sets the middle name of this candidate.
	 *
	 * @param middleName the middle name of this candidate
	 */
	public void setMiddleName(String middleName);

	/**
	 * Returns the last name of this candidate.
	 *
	 * @return the last name of this candidate
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this candidate.
	 *
	 * @param lastName the last name of this candidate
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the date of birth of this candidate.
	 *
	 * @return the date of birth of this candidate
	 */
	public Date getDateOfBirth();

	/**
	 * Sets the date of birth of this candidate.
	 *
	 * @param dateOfBirth the date of birth of this candidate
	 */
	public void setDateOfBirth(Date dateOfBirth);

	/**
	 * Returns the nationality of this candidate.
	 *
	 * @return the nationality of this candidate
	 */
	@AutoEscape
	public String getNationality();

	/**
	 * Sets the nationality of this candidate.
	 *
	 * @param nationality the nationality of this candidate
	 */
	public void setNationality(String nationality);

	/**
	 * Returns the marital status of this candidate.
	 *
	 * @return the marital status of this candidate
	 */
	public int getMaritalStatus();

	/**
	 * Sets the marital status of this candidate.
	 *
	 * @param maritalStatus the marital status of this candidate
	 */
	public void setMaritalStatus(int maritalStatus);

	/**
	 * Returns the street1 of this candidate.
	 *
	 * @return the street1 of this candidate
	 */
	@AutoEscape
	public String getStreet1();

	/**
	 * Sets the street1 of this candidate.
	 *
	 * @param street1 the street1 of this candidate
	 */
	public void setStreet1(String street1);

	/**
	 * Returns the street2 of this candidate.
	 *
	 * @return the street2 of this candidate
	 */
	@AutoEscape
	public String getStreet2();

	/**
	 * Sets the street2 of this candidate.
	 *
	 * @param street2 the street2 of this candidate
	 */
	public void setStreet2(String street2);

	/**
	 * Returns the street3 of this candidate.
	 *
	 * @return the street3 of this candidate
	 */
	@AutoEscape
	public String getStreet3();

	/**
	 * Sets the street3 of this candidate.
	 *
	 * @param street3 the street3 of this candidate
	 */
	public void setStreet3(String street3);

	/**
	 * Returns the city of this candidate.
	 *
	 * @return the city of this candidate
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this candidate.
	 *
	 * @param city the city of this candidate
	 */
	public void setCity(String city);

	/**
	 * Returns the zip of this candidate.
	 *
	 * @return the zip of this candidate
	 */
	public long getZip();

	/**
	 * Sets the zip of this candidate.
	 *
	 * @param zip the zip of this candidate
	 */
	public void setZip(long zip);

	/**
	 * Returns the country ID of this candidate.
	 *
	 * @return the country ID of this candidate
	 */
	public long getCountryId();

	/**
	 * Sets the country ID of this candidate.
	 *
	 * @param countryId the country ID of this candidate
	 */
	public void setCountryId(long countryId);

	/**
	 * Returns the personal email of this candidate.
	 *
	 * @return the personal email of this candidate
	 */
	@AutoEscape
	public String getPersonalEmail();

	/**
	 * Sets the personal email of this candidate.
	 *
	 * @param personalEmail the personal email of this candidate
	 */
	public void setPersonalEmail(String personalEmail);

	/**
	 * Returns the current ctc of this candidate.
	 *
	 * @return the current ctc of this candidate
	 */
	public long getCurrentCtc();

	/**
	 * Sets the current ctc of this candidate.
	 *
	 * @param currentCtc the current ctc of this candidate
	 */
	public void setCurrentCtc(long currentCtc);

	/**
	 * Returns the expected ctc of this candidate.
	 *
	 * @return the expected ctc of this candidate
	 */
	public long getExpectedCtc();

	/**
	 * Sets the expected ctc of this candidate.
	 *
	 * @param expectedCtc the expected ctc of this candidate
	 */
	public void setExpectedCtc(long expectedCtc);

	/**
	 * Returns the notice period of this candidate.
	 *
	 * @return the notice period of this candidate
	 */
	@AutoEscape
	public String getNoticePeriod();

	/**
	 * Sets the notice period of this candidate.
	 *
	 * @param noticePeriod the notice period of this candidate
	 */
	public void setNoticePeriod(String noticePeriod);

	/**
	 * Returns the resume ID of this candidate.
	 *
	 * @return the resume ID of this candidate
	 */
	public long getResumeId();

	/**
	 * Sets the resume ID of this candidate.
	 *
	 * @param resumeId the resume ID of this candidate
	 */
	public void setResumeId(long resumeId);

	/**
	 * Returns the resume path of this candidate.
	 *
	 * @return the resume path of this candidate
	 */
	@AutoEscape
	public String getResumePath();

	/**
	 * Sets the resume path of this candidate.
	 *
	 * @param resumePath the resume path of this candidate
	 */
	public void setResumePath(String resumePath);

	/**
	 * Returns the employee proof ID of this candidate.
	 *
	 * @return the employee proof ID of this candidate
	 */
	public long getEmployeeProofId();

	/**
	 * Sets the employee proof ID of this candidate.
	 *
	 * @param employeeProofId the employee proof ID of this candidate
	 */
	public void setEmployeeProofId(long employeeProofId);

	/**
	 * Returns the proof number of this candidate.
	 *
	 * @return the proof number of this candidate
	 */
	@AutoEscape
	public String getProofNumber();

	/**
	 * Sets the proof number of this candidate.
	 *
	 * @param proofNumber the proof number of this candidate
	 */
	public void setProofNumber(String proofNumber);

	/**
	 * Returns the gender of this candidate.
	 *
	 * @return the gender of this candidate
	 */
	public int getGender();

	/**
	 * Sets the gender of this candidate.
	 *
	 * @param gender the gender of this candidate
	 */
	public void setGender(int gender);

	/**
	 * Returns the status of this candidate.
	 *
	 * @return the status of this candidate
	 */
	public boolean getStatus();

	/**
	 * Returns <code>true</code> if this candidate is status.
	 *
	 * @return <code>true</code> if this candidate is status; <code>false</code> otherwise
	 */
	public boolean isStatus();

	/**
	 * Sets whether this candidate is status.
	 *
	 * @param status the status of this candidate
	 */
	public void setStatus(boolean status);

	/**
	 * Returns the short listed of this candidate.
	 *
	 * @return the short listed of this candidate
	 */
	public boolean getShortListed();

	/**
	 * Returns <code>true</code> if this candidate is short listed.
	 *
	 * @return <code>true</code> if this candidate is short listed; <code>false</code> otherwise
	 */
	public boolean isShortListed();

	/**
	 * Sets whether this candidate is short listed.
	 *
	 * @param shortListed the short listed of this candidate
	 */
	public void setShortListed(boolean shortListed);

	/**
	 * Returns the create date of this candidate.
	 *
	 * @return the create date of this candidate
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this candidate.
	 *
	 * @param createDate the create date of this candidate
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this candidate.
	 *
	 * @return the modified date of this candidate
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this candidate.
	 *
	 * @param modifiedDate the modified date of this candidate
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the create by of this candidate.
	 *
	 * @return the create by of this candidate
	 */
	public long getCreateBy();

	/**
	 * Sets the create by of this candidate.
	 *
	 * @param createBy the create by of this candidate
	 */
	public void setCreateBy(long createBy);

	/**
	 * Returns the modified by of this candidate.
	 *
	 * @return the modified by of this candidate
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this candidate.
	 *
	 * @param modifiedBy the modified by of this candidate
	 */
	public void setModifiedBy(long modifiedBy);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Candidate candidate);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Candidate> toCacheModel();

	@Override
	public Candidate toEscapedModel();

	@Override
	public Candidate toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}