/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.hrms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CandidateQualification service. Represents a row in the &quot;HRMS_CandidateQualification&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.hrms.model.impl.CandidateQualificationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.hrms.model.impl.CandidateQualificationImpl}.
 * </p>
 *
 * @author bhavik
 * @see CandidateQualification
 * @see com.hrms.model.impl.CandidateQualificationImpl
 * @see com.hrms.model.impl.CandidateQualificationModelImpl
 * @generated
 */
public interface CandidateQualificationModel extends BaseModel<CandidateQualification> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a candidate qualification model instance should use the {@link CandidateQualification} interface instead.
	 */

	/**
	 * Returns the primary key of this candidate qualification.
	 *
	 * @return the primary key of this candidate qualification
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this candidate qualification.
	 *
	 * @param primaryKey the primary key of this candidate qualification
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the candidate qualification ID of this candidate qualification.
	 *
	 * @return the candidate qualification ID of this candidate qualification
	 */
	public long getCandidateQualificationId();

	/**
	 * Sets the candidate qualification ID of this candidate qualification.
	 *
	 * @param candidateQualificationId the candidate qualification ID of this candidate qualification
	 */
	public void setCandidateQualificationId(long candidateQualificationId);

	/**
	 * Returns the candidate ID of this candidate qualification.
	 *
	 * @return the candidate ID of this candidate qualification
	 */
	public long getCandidateId();

	/**
	 * Sets the candidate ID of this candidate qualification.
	 *
	 * @param candidateId the candidate ID of this candidate qualification
	 */
	public void setCandidateId(long candidateId);

	/**
	 * Returns the degree name of this candidate qualification.
	 *
	 * @return the degree name of this candidate qualification
	 */
	@AutoEscape
	public String getDegreeName();

	/**
	 * Sets the degree name of this candidate qualification.
	 *
	 * @param degreeName the degree name of this candidate qualification
	 */
	public void setDegreeName(String degreeName);

	/**
	 * Returns the main subject of this candidate qualification.
	 *
	 * @return the main subject of this candidate qualification
	 */
	@AutoEscape
	public String getMainSubject();

	/**
	 * Sets the main subject of this candidate qualification.
	 *
	 * @param mainSubject the main subject of this candidate qualification
	 */
	public void setMainSubject(String mainSubject);

	/**
	 * Returns the university of this candidate qualification.
	 *
	 * @return the university of this candidate qualification
	 */
	@AutoEscape
	public String getUniversity();

	/**
	 * Sets the university of this candidate qualification.
	 *
	 * @param university the university of this candidate qualification
	 */
	public void setUniversity(String university);

	/**
	 * Returns the score of this candidate qualification.
	 *
	 * @return the score of this candidate qualification
	 */
	@AutoEscape
	public String getScore();

	/**
	 * Sets the score of this candidate qualification.
	 *
	 * @param score the score of this candidate qualification
	 */
	public void setScore(String score);

	/**
	 * Returns the start date of this candidate qualification.
	 *
	 * @return the start date of this candidate qualification
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this candidate qualification.
	 *
	 * @param startDate the start date of this candidate qualification
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the end date of this candidate qualification.
	 *
	 * @return the end date of this candidate qualification
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this candidate qualification.
	 *
	 * @param endDate the end date of this candidate qualification
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the create date of this candidate qualification.
	 *
	 * @return the create date of this candidate qualification
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this candidate qualification.
	 *
	 * @param createDate the create date of this candidate qualification
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this candidate qualification.
	 *
	 * @return the modified date of this candidate qualification
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this candidate qualification.
	 *
	 * @param modifiedDate the modified date of this candidate qualification
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the create by of this candidate qualification.
	 *
	 * @return the create by of this candidate qualification
	 */
	public long getCreateBy();

	/**
	 * Sets the create by of this candidate qualification.
	 *
	 * @param createBy the create by of this candidate qualification
	 */
	public void setCreateBy(long createBy);

	/**
	 * Returns the modified by of this candidate qualification.
	 *
	 * @return the modified by of this candidate qualification
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this candidate qualification.
	 *
	 * @param modifiedBy the modified by of this candidate qualification
	 */
	public void setModifiedBy(long modifiedBy);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(CandidateQualification candidateQualification);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CandidateQualification> toCacheModel();

	@Override
	public CandidateQualification toEscapedModel();

	@Override
	public CandidateQualification toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}