/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.hrms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the EmployeeType service. Represents a row in the &quot;HRMS_EmployeeType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.hrms.model.impl.EmployeeTypeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.hrms.model.impl.EmployeeTypeImpl}.
 * </p>
 *
 * @author yashpalsinh
 * @see EmployeeType
 * @see com.hrms.model.impl.EmployeeTypeImpl
 * @see com.hrms.model.impl.EmployeeTypeModelImpl
 * @generated
 */
public interface EmployeeTypeModel extends BaseModel<EmployeeType> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a employee type model instance should use the {@link EmployeeType} interface instead.
	 */

	/**
	 * Returns the primary key of this employee type.
	 *
	 * @return the primary key of this employee type
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this employee type.
	 *
	 * @param primaryKey the primary key of this employee type
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the employee type ID of this employee type.
	 *
	 * @return the employee type ID of this employee type
	 */
	public long getEmployeeTypeId();

	/**
	 * Sets the employee type ID of this employee type.
	 *
	 * @param employeeTypeId the employee type ID of this employee type
	 */
	public void setEmployeeTypeId(long employeeTypeId);

	/**
	 * Returns the employee type name of this employee type.
	 *
	 * @return the employee type name of this employee type
	 */
	@AutoEscape
	public String getEmployeeTypeName();

	/**
	 * Sets the employee type name of this employee type.
	 *
	 * @param employeeTypeName the employee type name of this employee type
	 */
	public void setEmployeeTypeName(String employeeTypeName);

	/**
	 * Returns the status of this employee type.
	 *
	 * @return the status of this employee type
	 */
	public boolean getStatus();

	/**
	 * Returns <code>true</code> if this employee type is status.
	 *
	 * @return <code>true</code> if this employee type is status; <code>false</code> otherwise
	 */
	public boolean isStatus();

	/**
	 * Sets whether this employee type is status.
	 *
	 * @param status the status of this employee type
	 */
	public void setStatus(boolean status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(EmployeeType employeeType);

	@Override
	public int hashCode();

	@Override
	public CacheModel<EmployeeType> toCacheModel();

	@Override
	public EmployeeType toEscapedModel();

	@Override
	public EmployeeType toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}