/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.hrms.model;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the EmployeeAttendance service. Represents a row in the &quot;HRMS_EmployeeAttendance&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.hrms.model.impl.EmployeeAttendanceModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.hrms.model.impl.EmployeeAttendanceImpl}.
 * </p>
 *
 * @author yashpalsinh
 * @see EmployeeAttendance
 * @see com.hrms.model.impl.EmployeeAttendanceImpl
 * @see com.hrms.model.impl.EmployeeAttendanceModelImpl
 * @generated
 */
public interface EmployeeAttendanceModel extends BaseModel<EmployeeAttendance> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a employee attendance model instance should use the {@link EmployeeAttendance} interface instead.
	 */

	/**
	 * Returns the primary key of this employee attendance.
	 *
	 * @return the primary key of this employee attendance
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this employee attendance.
	 *
	 * @param primaryKey the primary key of this employee attendance
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the attendance ID of this employee attendance.
	 *
	 * @return the attendance ID of this employee attendance
	 */
	public long getAttendanceId();

	/**
	 * Sets the attendance ID of this employee attendance.
	 *
	 * @param attendanceId the attendance ID of this employee attendance
	 */
	public void setAttendanceId(long attendanceId);

	/**
	 * Returns the user ID of this employee attendance.
	 *
	 * @return the user ID of this employee attendance
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this employee attendance.
	 *
	 * @param userId the user ID of this employee attendance
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this employee attendance.
	 *
	 * @return the user uuid of this employee attendance
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this employee attendance.
	 *
	 * @param userUuid the user uuid of this employee attendance
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the group ID of this employee attendance.
	 *
	 * @return the group ID of this employee attendance
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this employee attendance.
	 *
	 * @param groupId the group ID of this employee attendance
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this employee attendance.
	 *
	 * @return the company ID of this employee attendance
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this employee attendance.
	 *
	 * @param companyId the company ID of this employee attendance
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the attendance date of this employee attendance.
	 *
	 * @return the attendance date of this employee attendance
	 */
	public Date getAttendanceDate();

	/**
	 * Sets the attendance date of this employee attendance.
	 *
	 * @param attendanceDate the attendance date of this employee attendance
	 */
	public void setAttendanceDate(Date attendanceDate);

	/**
	 * Returns the signin time of this employee attendance.
	 *
	 * @return the signin time of this employee attendance
	 */
	public Date getSigninTime();

	/**
	 * Sets the signin time of this employee attendance.
	 *
	 * @param signinTime the signin time of this employee attendance
	 */
	public void setSigninTime(Date signinTime);

	/**
	 * Returns the signout time of this employee attendance.
	 *
	 * @return the signout time of this employee attendance
	 */
	public Date getSignoutTime();

	/**
	 * Sets the signout time of this employee attendance.
	 *
	 * @param signoutTime the signout time of this employee attendance
	 */
	public void setSignoutTime(Date signoutTime);

	/**
	 * Returns the total time of this employee attendance.
	 *
	 * @return the total time of this employee attendance
	 */
	public Date getTotalTime();

	/**
	 * Sets the total time of this employee attendance.
	 *
	 * @param totalTime the total time of this employee attendance
	 */
	public void setTotalTime(Date totalTime);

	/**
	 * Returns the approved of this employee attendance.
	 *
	 * @return the approved of this employee attendance
	 */
	public boolean getApproved();

	/**
	 * Returns <code>true</code> if this employee attendance is approved.
	 *
	 * @return <code>true</code> if this employee attendance is approved; <code>false</code> otherwise
	 */
	public boolean isApproved();

	/**
	 * Sets whether this employee attendance is approved.
	 *
	 * @param approved the approved of this employee attendance
	 */
	public void setApproved(boolean approved);

	/**
	 * Returns the approved by of this employee attendance.
	 *
	 * @return the approved by of this employee attendance
	 */
	public long getApprovedBy();

	/**
	 * Sets the approved by of this employee attendance.
	 *
	 * @param approvedBy the approved by of this employee attendance
	 */
	public void setApprovedBy(long approvedBy);

	/**
	 * Returns the create date of this employee attendance.
	 *
	 * @return the create date of this employee attendance
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this employee attendance.
	 *
	 * @param createDate the create date of this employee attendance
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this employee attendance.
	 *
	 * @return the modified date of this employee attendance
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this employee attendance.
	 *
	 * @param modifiedDate the modified date of this employee attendance
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the create by of this employee attendance.
	 *
	 * @return the create by of this employee attendance
	 */
	public long getCreateBy();

	/**
	 * Sets the create by of this employee attendance.
	 *
	 * @param createBy the create by of this employee attendance
	 */
	public void setCreateBy(long createBy);

	/**
	 * Returns the modified by of this employee attendance.
	 *
	 * @return the modified by of this employee attendance
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this employee attendance.
	 *
	 * @param modifiedBy the modified by of this employee attendance
	 */
	public void setModifiedBy(long modifiedBy);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(EmployeeAttendance employeeAttendance);

	@Override
	public int hashCode();

	@Override
	public CacheModel<EmployeeAttendance> toCacheModel();

	@Override
	public EmployeeAttendance toEscapedModel();

	@Override
	public EmployeeAttendance toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}