/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.hrms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the EmployeeAchivement service. Represents a row in the &quot;HRMS_EmployeeAchivement&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.hrms.model.impl.EmployeeAchivementModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.hrms.model.impl.EmployeeAchivementImpl}.
 * </p>
 *
 * @author yashpalsinh
 * @see EmployeeAchivement
 * @see com.hrms.model.impl.EmployeeAchivementImpl
 * @see com.hrms.model.impl.EmployeeAchivementModelImpl
 * @generated
 */
public interface EmployeeAchivementModel extends BaseModel<EmployeeAchivement> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a employee achivement model instance should use the {@link EmployeeAchivement} interface instead.
	 */

	/**
	 * Returns the primary key of this employee achivement.
	 *
	 * @return the primary key of this employee achivement
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this employee achivement.
	 *
	 * @param primaryKey the primary key of this employee achivement
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the employee achivement ID of this employee achivement.
	 *
	 * @return the employee achivement ID of this employee achivement
	 */
	public long getEmployeeAchivementId();

	/**
	 * Sets the employee achivement ID of this employee achivement.
	 *
	 * @param employeeAchivementId the employee achivement ID of this employee achivement
	 */
	public void setEmployeeAchivementId(long employeeAchivementId);

	/**
	 * Returns the achived by of this employee achivement.
	 *
	 * @return the achived by of this employee achivement
	 */
	public long getAchivedBy();

	/**
	 * Sets the achived by of this employee achivement.
	 *
	 * @param achivedBy the achived by of this employee achivement
	 */
	public void setAchivedBy(long achivedBy);

	/**
	 * Returns the group ID of this employee achivement.
	 *
	 * @return the group ID of this employee achivement
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this employee achivement.
	 *
	 * @param groupId the group ID of this employee achivement
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this employee achivement.
	 *
	 * @return the company ID of this employee achivement
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this employee achivement.
	 *
	 * @param companyId the company ID of this employee achivement
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the achivement date of this employee achivement.
	 *
	 * @return the achivement date of this employee achivement
	 */
	public Date getAchivementDate();

	/**
	 * Sets the achivement date of this employee achivement.
	 *
	 * @param achivementDate the achivement date of this employee achivement
	 */
	public void setAchivementDate(Date achivementDate);

	/**
	 * Returns the achivement title of this employee achivement.
	 *
	 * @return the achivement title of this employee achivement
	 */
	@AutoEscape
	public String getAchivementTitle();

	/**
	 * Sets the achivement title of this employee achivement.
	 *
	 * @param achivementTitle the achivement title of this employee achivement
	 */
	public void setAchivementTitle(String achivementTitle);

	/**
	 * Returns the achivement discription of this employee achivement.
	 *
	 * @return the achivement discription of this employee achivement
	 */
	@AutoEscape
	public String getAchivementDiscription();

	/**
	 * Sets the achivement discription of this employee achivement.
	 *
	 * @param achivementDiscription the achivement discription of this employee achivement
	 */
	public void setAchivementDiscription(String achivementDiscription);

	/**
	 * Returns the status of this employee achivement.
	 *
	 * @return the status of this employee achivement
	 */
	public boolean getStatus();

	/**
	 * Returns <code>true</code> if this employee achivement is status.
	 *
	 * @return <code>true</code> if this employee achivement is status; <code>false</code> otherwise
	 */
	public boolean isStatus();

	/**
	 * Sets whether this employee achivement is status.
	 *
	 * @param status the status of this employee achivement
	 */
	public void setStatus(boolean status);

	/**
	 * Returns the create date of this employee achivement.
	 *
	 * @return the create date of this employee achivement
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this employee achivement.
	 *
	 * @param createDate the create date of this employee achivement
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this employee achivement.
	 *
	 * @return the modified date of this employee achivement
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this employee achivement.
	 *
	 * @param modifiedDate the modified date of this employee achivement
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the create by of this employee achivement.
	 *
	 * @return the create by of this employee achivement
	 */
	public long getCreateBy();

	/**
	 * Sets the create by of this employee achivement.
	 *
	 * @param createBy the create by of this employee achivement
	 */
	public void setCreateBy(long createBy);

	/**
	 * Returns the modified by of this employee achivement.
	 *
	 * @return the modified by of this employee achivement
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this employee achivement.
	 *
	 * @param modifiedBy the modified by of this employee achivement
	 */
	public void setModifiedBy(long modifiedBy);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(EmployeeAchivement employeeAchivement);

	@Override
	public int hashCode();

	@Override
	public CacheModel<EmployeeAchivement> toCacheModel();

	@Override
	public EmployeeAchivement toEscapedModel();

	@Override
	public EmployeeAchivement toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}