/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.hrms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the EmployeeTimesheet service. Represents a row in the &quot;HRMS_EmployeeTimesheet&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.hrms.model.impl.EmployeeTimesheetModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.hrms.model.impl.EmployeeTimesheetImpl}.
 * </p>
 *
 * @author yashpalsinh
 * @see EmployeeTimesheet
 * @see com.hrms.model.impl.EmployeeTimesheetImpl
 * @see com.hrms.model.impl.EmployeeTimesheetModelImpl
 * @generated
 */
public interface EmployeeTimesheetModel extends BaseModel<EmployeeTimesheet> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a employee timesheet model instance should use the {@link EmployeeTimesheet} interface instead.
	 */

	/**
	 * Returns the primary key of this employee timesheet.
	 *
	 * @return the primary key of this employee timesheet
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this employee timesheet.
	 *
	 * @param primaryKey the primary key of this employee timesheet
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the timesheet ID of this employee timesheet.
	 *
	 * @return the timesheet ID of this employee timesheet
	 */
	public long getTimesheetId();

	/**
	 * Sets the timesheet ID of this employee timesheet.
	 *
	 * @param timesheetId the timesheet ID of this employee timesheet
	 */
	public void setTimesheetId(long timesheetId);

	/**
	 * Returns the user ID of this employee timesheet.
	 *
	 * @return the user ID of this employee timesheet
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this employee timesheet.
	 *
	 * @param userId the user ID of this employee timesheet
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this employee timesheet.
	 *
	 * @return the user uuid of this employee timesheet
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this employee timesheet.
	 *
	 * @param userUuid the user uuid of this employee timesheet
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the group ID of this employee timesheet.
	 *
	 * @return the group ID of this employee timesheet
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this employee timesheet.
	 *
	 * @param groupId the group ID of this employee timesheet
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this employee timesheet.
	 *
	 * @return the company ID of this employee timesheet
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this employee timesheet.
	 *
	 * @param companyId the company ID of this employee timesheet
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the task title of this employee timesheet.
	 *
	 * @return the task title of this employee timesheet
	 */
	@AutoEscape
	public String getTaskTitle();

	/**
	 * Sets the task title of this employee timesheet.
	 *
	 * @param taskTitle the task title of this employee timesheet
	 */
	public void setTaskTitle(String taskTitle);

	/**
	 * Returns the task description of this employee timesheet.
	 *
	 * @return the task description of this employee timesheet
	 */
	@AutoEscape
	public String getTaskDescription();

	/**
	 * Sets the task description of this employee timesheet.
	 *
	 * @param taskDescription the task description of this employee timesheet
	 */
	public void setTaskDescription(String taskDescription);

	/**
	 * Returns the task starttime of this employee timesheet.
	 *
	 * @return the task starttime of this employee timesheet
	 */
	public Date getTaskStarttime();

	/**
	 * Sets the task starttime of this employee timesheet.
	 *
	 * @param taskStarttime the task starttime of this employee timesheet
	 */
	public void setTaskStarttime(Date taskStarttime);

	/**
	 * Returns the task endtime of this employee timesheet.
	 *
	 * @return the task endtime of this employee timesheet
	 */
	public Date getTaskEndtime();

	/**
	 * Sets the task endtime of this employee timesheet.
	 *
	 * @param taskEndtime the task endtime of this employee timesheet
	 */
	public void setTaskEndtime(Date taskEndtime);

	/**
	 * Returns the task date of this employee timesheet.
	 *
	 * @return the task date of this employee timesheet
	 */
	public Date getTaskDate();

	/**
	 * Sets the task date of this employee timesheet.
	 *
	 * @param taskDate the task date of this employee timesheet
	 */
	public void setTaskDate(Date taskDate);

	/**
	 * Returns the duration of this employee timesheet.
	 *
	 * @return the duration of this employee timesheet
	 */
	@AutoEscape
	public String getDuration();

	/**
	 * Sets the duration of this employee timesheet.
	 *
	 * @param duration the duration of this employee timesheet
	 */
	public void setDuration(String duration);

	/**
	 * Returns the task completed of this employee timesheet.
	 *
	 * @return the task completed of this employee timesheet
	 */
	public boolean getTaskCompleted();

	/**
	 * Returns <code>true</code> if this employee timesheet is task completed.
	 *
	 * @return <code>true</code> if this employee timesheet is task completed; <code>false</code> otherwise
	 */
	public boolean isTaskCompleted();

	/**
	 * Sets whether this employee timesheet is task completed.
	 *
	 * @param taskCompleted the task completed of this employee timesheet
	 */
	public void setTaskCompleted(boolean taskCompleted);

	/**
	 * Returns the billable of this employee timesheet.
	 *
	 * @return the billable of this employee timesheet
	 */
	public boolean getBillable();

	/**
	 * Returns <code>true</code> if this employee timesheet is billable.
	 *
	 * @return <code>true</code> if this employee timesheet is billable; <code>false</code> otherwise
	 */
	public boolean isBillable();

	/**
	 * Sets whether this employee timesheet is billable.
	 *
	 * @param billable the billable of this employee timesheet
	 */
	public void setBillable(boolean billable);

	/**
	 * Returns the billed of this employee timesheet.
	 *
	 * @return the billed of this employee timesheet
	 */
	public boolean getBilled();

	/**
	 * Returns <code>true</code> if this employee timesheet is billed.
	 *
	 * @return <code>true</code> if this employee timesheet is billed; <code>false</code> otherwise
	 */
	public boolean isBilled();

	/**
	 * Sets whether this employee timesheet is billed.
	 *
	 * @param billed the billed of this employee timesheet
	 */
	public void setBilled(boolean billed);

	/**
	 * Returns the create date of this employee timesheet.
	 *
	 * @return the create date of this employee timesheet
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this employee timesheet.
	 *
	 * @param createDate the create date of this employee timesheet
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this employee timesheet.
	 *
	 * @return the modified date of this employee timesheet
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this employee timesheet.
	 *
	 * @param modifiedDate the modified date of this employee timesheet
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the create by of this employee timesheet.
	 *
	 * @return the create by of this employee timesheet
	 */
	public long getCreateBy();

	/**
	 * Sets the create by of this employee timesheet.
	 *
	 * @param createBy the create by of this employee timesheet
	 */
	public void setCreateBy(long createBy);

	/**
	 * Returns the modified by of this employee timesheet.
	 *
	 * @return the modified by of this employee timesheet
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this employee timesheet.
	 *
	 * @param modifiedBy the modified by of this employee timesheet
	 */
	public void setModifiedBy(long modifiedBy);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(EmployeeTimesheet employeeTimesheet);

	@Override
	public int hashCode();

	@Override
	public CacheModel<EmployeeTimesheet> toCacheModel();

	@Override
	public EmployeeTimesheet toEscapedModel();

	@Override
	public EmployeeTimesheet toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}