/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.hrms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the EmployeeWarning service. Represents a row in the &quot;HRMS_EmployeeWarning&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.hrms.model.impl.EmployeeWarningModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.hrms.model.impl.EmployeeWarningImpl}.
 * </p>
 *
 * @author bhavik
 * @see EmployeeWarning
 * @see com.hrms.model.impl.EmployeeWarningImpl
 * @see com.hrms.model.impl.EmployeeWarningModelImpl
 * @generated
 */
public interface EmployeeWarningModel extends BaseModel<EmployeeWarning> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a employee warning model instance should use the {@link EmployeeWarning} interface instead.
	 */

	/**
	 * Returns the primary key of this employee warning.
	 *
	 * @return the primary key of this employee warning
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this employee warning.
	 *
	 * @param primaryKey the primary key of this employee warning
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the employee warning ID of this employee warning.
	 *
	 * @return the employee warning ID of this employee warning
	 */
	public long getEmployeeWarningId();

	/**
	 * Sets the employee warning ID of this employee warning.
	 *
	 * @param employeeWarningId the employee warning ID of this employee warning
	 */
	public void setEmployeeWarningId(long employeeWarningId);

	/**
	 * Returns the warning to of this employee warning.
	 *
	 * @return the warning to of this employee warning
	 */
	public long getWarningTo();

	/**
	 * Sets the warning to of this employee warning.
	 *
	 * @param warningTo the warning to of this employee warning
	 */
	public void setWarningTo(long warningTo);

	/**
	 * Returns the group ID of this employee warning.
	 *
	 * @return the group ID of this employee warning
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this employee warning.
	 *
	 * @param groupId the group ID of this employee warning
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this employee warning.
	 *
	 * @return the company ID of this employee warning
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this employee warning.
	 *
	 * @param companyId the company ID of this employee warning
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the warning date of this employee warning.
	 *
	 * @return the warning date of this employee warning
	 */
	public Date getWarningDate();

	/**
	 * Sets the warning date of this employee warning.
	 *
	 * @param warningDate the warning date of this employee warning
	 */
	public void setWarningDate(Date warningDate);

	/**
	 * Returns the warning subject of this employee warning.
	 *
	 * @return the warning subject of this employee warning
	 */
	@AutoEscape
	public String getWarningSubject();

	/**
	 * Sets the warning subject of this employee warning.
	 *
	 * @param warningSubject the warning subject of this employee warning
	 */
	public void setWarningSubject(String warningSubject);

	/**
	 * Returns the status of this employee warning.
	 *
	 * @return the status of this employee warning
	 */
	public boolean getStatus();

	/**
	 * Returns <code>true</code> if this employee warning is status.
	 *
	 * @return <code>true</code> if this employee warning is status; <code>false</code> otherwise
	 */
	public boolean isStatus();

	/**
	 * Sets whether this employee warning is status.
	 *
	 * @param status the status of this employee warning
	 */
	public void setStatus(boolean status);

	/**
	 * Returns the warning by of this employee warning.
	 *
	 * @return the warning by of this employee warning
	 */
	public long getWarningBy();

	/**
	 * Sets the warning by of this employee warning.
	 *
	 * @param warningBy the warning by of this employee warning
	 */
	public void setWarningBy(long warningBy);

	/**
	 * Returns the modified date of this employee warning.
	 *
	 * @return the modified date of this employee warning
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this employee warning.
	 *
	 * @param modifiedDate the modified date of this employee warning
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the create by of this employee warning.
	 *
	 * @return the create by of this employee warning
	 */
	public long getCreateBy();

	/**
	 * Sets the create by of this employee warning.
	 *
	 * @param createBy the create by of this employee warning
	 */
	public void setCreateBy(long createBy);

	/**
	 * Returns the modified by of this employee warning.
	 *
	 * @return the modified by of this employee warning
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this employee warning.
	 *
	 * @param modifiedBy the modified by of this employee warning
	 */
	public void setModifiedBy(long modifiedBy);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(EmployeeWarning employeeWarning);

	@Override
	public int hashCode();

	@Override
	public CacheModel<EmployeeWarning> toCacheModel();

	@Override
	public EmployeeWarning toEscapedModel();

	@Override
	public EmployeeWarning toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}