/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.hrms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the EmployeeDepartment service. Represents a row in the &quot;HRMS_EmployeeDepartment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.hrms.model.impl.EmployeeDepartmentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.hrms.model.impl.EmployeeDepartmentImpl}.
 * </p>
 *
 * @author yashpalsinh
 * @see EmployeeDepartment
 * @see com.hrms.model.impl.EmployeeDepartmentImpl
 * @see com.hrms.model.impl.EmployeeDepartmentModelImpl
 * @generated
 */
public interface EmployeeDepartmentModel extends BaseModel<EmployeeDepartment> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a employee department model instance should use the {@link EmployeeDepartment} interface instead.
	 */

	/**
	 * Returns the primary key of this employee department.
	 *
	 * @return the primary key of this employee department
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this employee department.
	 *
	 * @param primaryKey the primary key of this employee department
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the employee department ID of this employee department.
	 *
	 * @return the employee department ID of this employee department
	 */
	public long getEmployeeDepartmentId();

	/**
	 * Sets the employee department ID of this employee department.
	 *
	 * @param employeeDepartmentId the employee department ID of this employee department
	 */
	public void setEmployeeDepartmentId(long employeeDepartmentId);

	/**
	 * Returns the department name of this employee department.
	 *
	 * @return the department name of this employee department
	 */
	@AutoEscape
	public String getDepartmentName();

	/**
	 * Sets the department name of this employee department.
	 *
	 * @param departmentName the department name of this employee department
	 */
	public void setDepartmentName(String departmentName);

	/**
	 * Returns the status of this employee department.
	 *
	 * @return the status of this employee department
	 */
	public boolean getStatus();

	/**
	 * Returns <code>true</code> if this employee department is status.
	 *
	 * @return <code>true</code> if this employee department is status; <code>false</code> otherwise
	 */
	public boolean isStatus();

	/**
	 * Sets whether this employee department is status.
	 *
	 * @param status the status of this employee department
	 */
	public void setStatus(boolean status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(EmployeeDepartment employeeDepartment);

	@Override
	public int hashCode();

	@Override
	public CacheModel<EmployeeDepartment> toCacheModel();

	@Override
	public EmployeeDepartment toEscapedModel();

	@Override
	public EmployeeDepartment toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}