/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.hrms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the EmployeeQualification service. Represents a row in the &quot;HRMS_EmployeeQualification&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.hrms.model.impl.EmployeeQualificationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.hrms.model.impl.EmployeeQualificationImpl}.
 * </p>
 *
 * @author bhavik
 * @see EmployeeQualification
 * @see com.hrms.model.impl.EmployeeQualificationImpl
 * @see com.hrms.model.impl.EmployeeQualificationModelImpl
 * @generated
 */
public interface EmployeeQualificationModel extends BaseModel<EmployeeQualification> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a employee qualification model instance should use the {@link EmployeeQualification} interface instead.
	 */

	/**
	 * Returns the primary key of this employee qualification.
	 *
	 * @return the primary key of this employee qualification
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this employee qualification.
	 *
	 * @param primaryKey the primary key of this employee qualification
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the employee qualification ID of this employee qualification.
	 *
	 * @return the employee qualification ID of this employee qualification
	 */
	public long getEmployeeQualificationId();

	/**
	 * Sets the employee qualification ID of this employee qualification.
	 *
	 * @param employeeQualificationId the employee qualification ID of this employee qualification
	 */
	public void setEmployeeQualificationId(long employeeQualificationId);

	/**
	 * Returns the user ID of this employee qualification.
	 *
	 * @return the user ID of this employee qualification
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this employee qualification.
	 *
	 * @param userId the user ID of this employee qualification
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this employee qualification.
	 *
	 * @return the user uuid of this employee qualification
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this employee qualification.
	 *
	 * @param userUuid the user uuid of this employee qualification
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the group ID of this employee qualification.
	 *
	 * @return the group ID of this employee qualification
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this employee qualification.
	 *
	 * @param groupId the group ID of this employee qualification
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this employee qualification.
	 *
	 * @return the company ID of this employee qualification
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this employee qualification.
	 *
	 * @param companyId the company ID of this employee qualification
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the degree name of this employee qualification.
	 *
	 * @return the degree name of this employee qualification
	 */
	@AutoEscape
	public String getDegreeName();

	/**
	 * Sets the degree name of this employee qualification.
	 *
	 * @param degreeName the degree name of this employee qualification
	 */
	public void setDegreeName(String degreeName);

	/**
	 * Returns the main subject of this employee qualification.
	 *
	 * @return the main subject of this employee qualification
	 */
	@AutoEscape
	public String getMainSubject();

	/**
	 * Sets the main subject of this employee qualification.
	 *
	 * @param mainSubject the main subject of this employee qualification
	 */
	public void setMainSubject(String mainSubject);

	/**
	 * Returns the university of this employee qualification.
	 *
	 * @return the university of this employee qualification
	 */
	@AutoEscape
	public String getUniversity();

	/**
	 * Sets the university of this employee qualification.
	 *
	 * @param university the university of this employee qualification
	 */
	public void setUniversity(String university);

	/**
	 * Returns the score of this employee qualification.
	 *
	 * @return the score of this employee qualification
	 */
	@AutoEscape
	public String getScore();

	/**
	 * Sets the score of this employee qualification.
	 *
	 * @param score the score of this employee qualification
	 */
	public void setScore(String score);

	/**
	 * Returns the start date of this employee qualification.
	 *
	 * @return the start date of this employee qualification
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this employee qualification.
	 *
	 * @param startDate the start date of this employee qualification
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the end date of this employee qualification.
	 *
	 * @return the end date of this employee qualification
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this employee qualification.
	 *
	 * @param endDate the end date of this employee qualification
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the create date of this employee qualification.
	 *
	 * @return the create date of this employee qualification
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this employee qualification.
	 *
	 * @param createDate the create date of this employee qualification
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this employee qualification.
	 *
	 * @return the modified date of this employee qualification
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this employee qualification.
	 *
	 * @param modifiedDate the modified date of this employee qualification
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the create by of this employee qualification.
	 *
	 * @return the create by of this employee qualification
	 */
	public long getCreateBy();

	/**
	 * Sets the create by of this employee qualification.
	 *
	 * @param createBy the create by of this employee qualification
	 */
	public void setCreateBy(long createBy);

	/**
	 * Returns the modified by of this employee qualification.
	 *
	 * @return the modified by of this employee qualification
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this employee qualification.
	 *
	 * @param modifiedBy the modified by of this employee qualification
	 */
	public void setModifiedBy(long modifiedBy);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(EmployeeQualification employeeQualification);

	@Override
	public int hashCode();

	@Override
	public CacheModel<EmployeeQualification> toCacheModel();

	@Override
	public EmployeeQualification toEscapedModel();

	@Override
	public EmployeeQualification toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}