/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.hrms.model;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the EmployeeLeave service. Represents a row in the &quot;HRMS_EmployeeLeave&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.hrms.model.impl.EmployeeLeaveModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.hrms.model.impl.EmployeeLeaveImpl}.
 * </p>
 *
 * @author bhavik
 * @see EmployeeLeave
 * @see com.hrms.model.impl.EmployeeLeaveImpl
 * @see com.hrms.model.impl.EmployeeLeaveModelImpl
 * @generated
 */
public interface EmployeeLeaveModel extends BaseModel<EmployeeLeave> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a employee leave model instance should use the {@link EmployeeLeave} interface instead.
	 */

	/**
	 * Returns the primary key of this employee leave.
	 *
	 * @return the primary key of this employee leave
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this employee leave.
	 *
	 * @param primaryKey the primary key of this employee leave
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the employee leave ID of this employee leave.
	 *
	 * @return the employee leave ID of this employee leave
	 */
	public long getEmployeeLeaveId();

	/**
	 * Sets the employee leave ID of this employee leave.
	 *
	 * @param employeeLeaveId the employee leave ID of this employee leave
	 */
	public void setEmployeeLeaveId(long employeeLeaveId);

	/**
	 * Returns the user ID of this employee leave.
	 *
	 * @return the user ID of this employee leave
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this employee leave.
	 *
	 * @param userId the user ID of this employee leave
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this employee leave.
	 *
	 * @return the user uuid of this employee leave
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this employee leave.
	 *
	 * @param userUuid the user uuid of this employee leave
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the group ID of this employee leave.
	 *
	 * @return the group ID of this employee leave
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this employee leave.
	 *
	 * @param groupId the group ID of this employee leave
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this employee leave.
	 *
	 * @return the company ID of this employee leave
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this employee leave.
	 *
	 * @param companyId the company ID of this employee leave
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the year of this employee leave.
	 *
	 * @return the year of this employee leave
	 */
	public int getYear();

	/**
	 * Sets the year of this employee leave.
	 *
	 * @param year the year of this employee leave
	 */
	public void setYear(int year);

	/**
	 * Returns the leaves carried over of this employee leave.
	 *
	 * @return the leaves carried over of this employee leave
	 */
	public int getLeavesCarriedOver();

	/**
	 * Sets the leaves carried over of this employee leave.
	 *
	 * @param leavesCarriedOver the leaves carried over of this employee leave
	 */
	public void setLeavesCarriedOver(int leavesCarriedOver);

	/**
	 * Returns the leaves taken this year of this employee leave.
	 *
	 * @return the leaves taken this year of this employee leave
	 */
	public int getLeavesTakenThisYear();

	/**
	 * Sets the leaves taken this year of this employee leave.
	 *
	 * @param leavesTakenThisYear the leaves taken this year of this employee leave
	 */
	public void setLeavesTakenThisYear(int leavesTakenThisYear);

	/**
	 * Returns the remaining leaves of this employee leave.
	 *
	 * @return the remaining leaves of this employee leave
	 */
	public int getRemainingLeaves();

	/**
	 * Sets the remaining leaves of this employee leave.
	 *
	 * @param remainingLeaves the remaining leaves of this employee leave
	 */
	public void setRemainingLeaves(int remainingLeaves);

	/**
	 * Returns the leave ID of this employee leave.
	 *
	 * @return the leave ID of this employee leave
	 */
	public long getLeaveId();

	/**
	 * Sets the leave ID of this employee leave.
	 *
	 * @param leaveId the leave ID of this employee leave
	 */
	public void setLeaveId(long leaveId);

	/**
	 * Returns the create date of this employee leave.
	 *
	 * @return the create date of this employee leave
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this employee leave.
	 *
	 * @param createDate the create date of this employee leave
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this employee leave.
	 *
	 * @return the modified date of this employee leave
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this employee leave.
	 *
	 * @param modifiedDate the modified date of this employee leave
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the create by of this employee leave.
	 *
	 * @return the create by of this employee leave
	 */
	public long getCreateBy();

	/**
	 * Sets the create by of this employee leave.
	 *
	 * @param createBy the create by of this employee leave
	 */
	public void setCreateBy(long createBy);

	/**
	 * Returns the modified by of this employee leave.
	 *
	 * @return the modified by of this employee leave
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this employee leave.
	 *
	 * @param modifiedBy the modified by of this employee leave
	 */
	public void setModifiedBy(long modifiedBy);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(EmployeeLeave employeeLeave);

	@Override
	public int hashCode();

	@Override
	public CacheModel<EmployeeLeave> toCacheModel();

	@Override
	public EmployeeLeave toEscapedModel();

	@Override
	public EmployeeLeave toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}