/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.hrms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the EmployeeSubDepartment service. Represents a row in the &quot;HRMS_EmployeeSubDepartment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.hrms.model.impl.EmployeeSubDepartmentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.hrms.model.impl.EmployeeSubDepartmentImpl}.
 * </p>
 *
 * @author bhavik
 * @see EmployeeSubDepartment
 * @see com.hrms.model.impl.EmployeeSubDepartmentImpl
 * @see com.hrms.model.impl.EmployeeSubDepartmentModelImpl
 * @generated
 */
public interface EmployeeSubDepartmentModel extends BaseModel<EmployeeSubDepartment> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a employee sub department model instance should use the {@link EmployeeSubDepartment} interface instead.
	 */

	/**
	 * Returns the primary key of this employee sub department.
	 *
	 * @return the primary key of this employee sub department
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this employee sub department.
	 *
	 * @param primaryKey the primary key of this employee sub department
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the employee sub department ID of this employee sub department.
	 *
	 * @return the employee sub department ID of this employee sub department
	 */
	public long getEmployeeSubDepartmentId();

	/**
	 * Sets the employee sub department ID of this employee sub department.
	 *
	 * @param employeeSubDepartmentId the employee sub department ID of this employee sub department
	 */
	public void setEmployeeSubDepartmentId(long employeeSubDepartmentId);

	/**
	 * Returns the sub department name of this employee sub department.
	 *
	 * @return the sub department name of this employee sub department
	 */
	@AutoEscape
	public String getSubDepartmentName();

	/**
	 * Sets the sub department name of this employee sub department.
	 *
	 * @param subDepartmentName the sub department name of this employee sub department
	 */
	public void setSubDepartmentName(String subDepartmentName);

	/**
	 * Returns the employee department ID of this employee sub department.
	 *
	 * @return the employee department ID of this employee sub department
	 */
	public long getEmployeeDepartmentId();

	/**
	 * Sets the employee department ID of this employee sub department.
	 *
	 * @param employeeDepartmentId the employee department ID of this employee sub department
	 */
	public void setEmployeeDepartmentId(long employeeDepartmentId);

	/**
	 * Returns the status of this employee sub department.
	 *
	 * @return the status of this employee sub department
	 */
	public boolean getStatus();

	/**
	 * Returns <code>true</code> if this employee sub department is status.
	 *
	 * @return <code>true</code> if this employee sub department is status; <code>false</code> otherwise
	 */
	public boolean isStatus();

	/**
	 * Sets whether this employee sub department is status.
	 *
	 * @param status the status of this employee sub department
	 */
	public void setStatus(boolean status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(EmployeeSubDepartment employeeSubDepartment);

	@Override
	public int hashCode();

	@Override
	public CacheModel<EmployeeSubDepartment> toCacheModel();

	@Override
	public EmployeeSubDepartment toEscapedModel();

	@Override
	public EmployeeSubDepartment toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}