/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.hrms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the EmployeePreviousCompany service. Represents a row in the &quot;HRMS_EmployeePreviousCompany&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.hrms.model.impl.EmployeePreviousCompanyModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.hrms.model.impl.EmployeePreviousCompanyImpl}.
 * </p>
 *
 * @author bhavik
 * @see EmployeePreviousCompany
 * @see com.hrms.model.impl.EmployeePreviousCompanyImpl
 * @see com.hrms.model.impl.EmployeePreviousCompanyModelImpl
 * @generated
 */
public interface EmployeePreviousCompanyModel extends BaseModel<EmployeePreviousCompany> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a employee previous company model instance should use the {@link EmployeePreviousCompany} interface instead.
	 */

	/**
	 * Returns the primary key of this employee previous company.
	 *
	 * @return the primary key of this employee previous company
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this employee previous company.
	 *
	 * @param primaryKey the primary key of this employee previous company
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the employee previous company ID of this employee previous company.
	 *
	 * @return the employee previous company ID of this employee previous company
	 */
	public long getEmployeePreviousCompanyId();

	/**
	 * Sets the employee previous company ID of this employee previous company.
	 *
	 * @param employeePreviousCompanyId the employee previous company ID of this employee previous company
	 */
	public void setEmployeePreviousCompanyId(long employeePreviousCompanyId);

	/**
	 * Returns the user ID of this employee previous company.
	 *
	 * @return the user ID of this employee previous company
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this employee previous company.
	 *
	 * @param userId the user ID of this employee previous company
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this employee previous company.
	 *
	 * @return the user uuid of this employee previous company
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this employee previous company.
	 *
	 * @param userUuid the user uuid of this employee previous company
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the group ID of this employee previous company.
	 *
	 * @return the group ID of this employee previous company
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this employee previous company.
	 *
	 * @param groupId the group ID of this employee previous company
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this employee previous company.
	 *
	 * @return the company ID of this employee previous company
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this employee previous company.
	 *
	 * @param companyId the company ID of this employee previous company
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the company name of this employee previous company.
	 *
	 * @return the company name of this employee previous company
	 */
	@AutoEscape
	public String getCompanyName();

	/**
	 * Sets the company name of this employee previous company.
	 *
	 * @param companyName the company name of this employee previous company
	 */
	public void setCompanyName(String companyName);

	/**
	 * Returns the job title of this employee previous company.
	 *
	 * @return the job title of this employee previous company
	 */
	@AutoEscape
	public String getJobTitle();

	/**
	 * Sets the job title of this employee previous company.
	 *
	 * @param jobTitle the job title of this employee previous company
	 */
	public void setJobTitle(String jobTitle);

	/**
	 * Returns the job discription of this employee previous company.
	 *
	 * @return the job discription of this employee previous company
	 */
	@AutoEscape
	public String getJobDiscription();

	/**
	 * Sets the job discription of this employee previous company.
	 *
	 * @param jobDiscription the job discription of this employee previous company
	 */
	public void setJobDiscription(String jobDiscription);

	/**
	 * Returns the start date of this employee previous company.
	 *
	 * @return the start date of this employee previous company
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this employee previous company.
	 *
	 * @param startDate the start date of this employee previous company
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the end date of this employee previous company.
	 *
	 * @return the end date of this employee previous company
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this employee previous company.
	 *
	 * @param endDate the end date of this employee previous company
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the create date of this employee previous company.
	 *
	 * @return the create date of this employee previous company
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this employee previous company.
	 *
	 * @param createDate the create date of this employee previous company
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this employee previous company.
	 *
	 * @return the modified date of this employee previous company
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this employee previous company.
	 *
	 * @param modifiedDate the modified date of this employee previous company
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the create by of this employee previous company.
	 *
	 * @return the create by of this employee previous company
	 */
	public long getCreateBy();

	/**
	 * Sets the create by of this employee previous company.
	 *
	 * @param createBy the create by of this employee previous company
	 */
	public void setCreateBy(long createBy);

	/**
	 * Returns the modified by of this employee previous company.
	 *
	 * @return the modified by of this employee previous company
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this employee previous company.
	 *
	 * @param modifiedBy the modified by of this employee previous company
	 */
	public void setModifiedBy(long modifiedBy);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(EmployeePreviousCompany employeePreviousCompany);

	@Override
	public int hashCode();

	@Override
	public CacheModel<EmployeePreviousCompany> toCacheModel();

	@Override
	public EmployeePreviousCompany toEscapedModel();

	@Override
	public EmployeePreviousCompany toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}