/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.hrms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the EmployeeLanguageDetail service. Represents a row in the &quot;HRMS_EmployeeLanguageDetail&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.hrms.model.impl.EmployeeLanguageDetailModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.hrms.model.impl.EmployeeLanguageDetailImpl}.
 * </p>
 *
 * @author yashpalsinh
 * @see EmployeeLanguageDetail
 * @see com.hrms.model.impl.EmployeeLanguageDetailImpl
 * @see com.hrms.model.impl.EmployeeLanguageDetailModelImpl
 * @generated
 */
public interface EmployeeLanguageDetailModel extends BaseModel<EmployeeLanguageDetail> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a employee language detail model instance should use the {@link EmployeeLanguageDetail} interface instead.
	 */

	/**
	 * Returns the primary key of this employee language detail.
	 *
	 * @return the primary key of this employee language detail
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this employee language detail.
	 *
	 * @param primaryKey the primary key of this employee language detail
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the employee language detail ID of this employee language detail.
	 *
	 * @return the employee language detail ID of this employee language detail
	 */
	public long getEmployeeLanguageDetailId();

	/**
	 * Sets the employee language detail ID of this employee language detail.
	 *
	 * @param employeeLanguageDetailId the employee language detail ID of this employee language detail
	 */
	public void setEmployeeLanguageDetailId(long employeeLanguageDetailId);

	/**
	 * Returns the user ID of this employee language detail.
	 *
	 * @return the user ID of this employee language detail
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this employee language detail.
	 *
	 * @param userId the user ID of this employee language detail
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this employee language detail.
	 *
	 * @return the user uuid of this employee language detail
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this employee language detail.
	 *
	 * @param userUuid the user uuid of this employee language detail
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the group ID of this employee language detail.
	 *
	 * @return the group ID of this employee language detail
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this employee language detail.
	 *
	 * @param groupId the group ID of this employee language detail
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this employee language detail.
	 *
	 * @return the company ID of this employee language detail
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this employee language detail.
	 *
	 * @param companyId the company ID of this employee language detail
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the language name of this employee language detail.
	 *
	 * @return the language name of this employee language detail
	 */
	@AutoEscape
	public String getLanguageName();

	/**
	 * Sets the language name of this employee language detail.
	 *
	 * @param languageName the language name of this employee language detail
	 */
	public void setLanguageName(String languageName);

	/**
	 * Returns the read of this employee language detail.
	 *
	 * @return the read of this employee language detail
	 */
	public boolean getRead();

	/**
	 * Returns <code>true</code> if this employee language detail is read.
	 *
	 * @return <code>true</code> if this employee language detail is read; <code>false</code> otherwise
	 */
	public boolean isRead();

	/**
	 * Sets whether this employee language detail is read.
	 *
	 * @param read the read of this employee language detail
	 */
	public void setRead(boolean read);

	/**
	 * Returns the write of this employee language detail.
	 *
	 * @return the write of this employee language detail
	 */
	public boolean getWrite();

	/**
	 * Returns <code>true</code> if this employee language detail is write.
	 *
	 * @return <code>true</code> if this employee language detail is write; <code>false</code> otherwise
	 */
	public boolean isWrite();

	/**
	 * Sets whether this employee language detail is write.
	 *
	 * @param write the write of this employee language detail
	 */
	public void setWrite(boolean write);

	/**
	 * Returns the speak of this employee language detail.
	 *
	 * @return the speak of this employee language detail
	 */
	public boolean getSpeak();

	/**
	 * Returns <code>true</code> if this employee language detail is speak.
	 *
	 * @return <code>true</code> if this employee language detail is speak; <code>false</code> otherwise
	 */
	public boolean isSpeak();

	/**
	 * Sets whether this employee language detail is speak.
	 *
	 * @param speak the speak of this employee language detail
	 */
	public void setSpeak(boolean speak);

	/**
	 * Returns the create date of this employee language detail.
	 *
	 * @return the create date of this employee language detail
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this employee language detail.
	 *
	 * @param createDate the create date of this employee language detail
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this employee language detail.
	 *
	 * @return the modified date of this employee language detail
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this employee language detail.
	 *
	 * @param modifiedDate the modified date of this employee language detail
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the create by of this employee language detail.
	 *
	 * @return the create by of this employee language detail
	 */
	public long getCreateBy();

	/**
	 * Sets the create by of this employee language detail.
	 *
	 * @param createBy the create by of this employee language detail
	 */
	public void setCreateBy(long createBy);

	/**
	 * Returns the modified by of this employee language detail.
	 *
	 * @return the modified by of this employee language detail
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this employee language detail.
	 *
	 * @param modifiedBy the modified by of this employee language detail
	 */
	public void setModifiedBy(long modifiedBy);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(EmployeeLanguageDetail employeeLanguageDetail);

	@Override
	public int hashCode();

	@Override
	public CacheModel<EmployeeLanguageDetail> toCacheModel();

	@Override
	public EmployeeLanguageDetail toEscapedModel();

	@Override
	public EmployeeLanguageDetail toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}