/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.hrms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Proof service. Represents a row in the &quot;HRMS_Proof&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.hrms.model.impl.ProofModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.hrms.model.impl.ProofImpl}.
 * </p>
 *
 * @author yashpalsinh
 * @see Proof
 * @see com.hrms.model.impl.ProofImpl
 * @see com.hrms.model.impl.ProofModelImpl
 * @generated
 */
public interface ProofModel extends BaseModel<Proof> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a proof model instance should use the {@link Proof} interface instead.
	 */

	/**
	 * Returns the primary key of this proof.
	 *
	 * @return the primary key of this proof
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this proof.
	 *
	 * @param primaryKey the primary key of this proof
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the proof ID of this proof.
	 *
	 * @return the proof ID of this proof
	 */
	public long getProofId();

	/**
	 * Sets the proof ID of this proof.
	 *
	 * @param proofId the proof ID of this proof
	 */
	public void setProofId(long proofId);

	/**
	 * Returns the proof type of this proof.
	 *
	 * @return the proof type of this proof
	 */
	@AutoEscape
	public String getProofType();

	/**
	 * Sets the proof type of this proof.
	 *
	 * @param proofType the proof type of this proof
	 */
	public void setProofType(String proofType);

	/**
	 * Returns the status of this proof.
	 *
	 * @return the status of this proof
	 */
	public boolean getStatus();

	/**
	 * Returns <code>true</code> if this proof is status.
	 *
	 * @return <code>true</code> if this proof is status; <code>false</code> otherwise
	 */
	public boolean isStatus();

	/**
	 * Sets whether this proof is status.
	 *
	 * @param status the status of this proof
	 */
	public void setStatus(boolean status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Proof proof);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Proof> toCacheModel();

	@Override
	public Proof toEscapedModel();

	@Override
	public Proof toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}